### ISSUE TITLE
Selector Pre-Trained Models

### ISSUE THREAD

**Issue by TambourineMan42** [google/active-qa#11]
I was wondering where I can find (or if you plan to release) the Selector pre-trained models that achieved ~47.5 F1 score

**Comment by rodrigonogueira4** [comment]
Sorry about the delay.. we will released it soon.

**Comment by J-Fo-S** [comment]
Hi, sorry to be a nuisance but would you @rodrigonogueira4 be able to provide rough date of when 'soon' is? I need to work with this model very soon, but unfortunately training the selector is not as straightforward (to me) as simply running the save and load calls to the selector_keras.py module. At the moment, running reformulator_and_selector_training.py with 'enable_selector_training' true just results in an endless loop of the '_run_eval_with_selector' process, which seems odd because, of course, I haven't trained the selector yet.   

While I'm happy to figure out all this on my own, I'd rather not spend the time if the pre-trained selector model will be released, say in a week. Thanks in advance for any update you can provide regarding the timeframe for this.

**Comment by rodrigonogueira4** [comment]
Sorry about the late reply. We added a link to a Selector checkpoint to the README file. Feel free to reopen this issue in can you experience any problem.
